spring.application.name=capgemini

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/employee
spring.datasource.username=postgres
spring.datasource.password=Aman@15112003

#Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update

#Show SQL statements in the console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
